In [3]:
import tensorflow as tf

In [2]:
sess = tf.Session()

In [3]:
hello = tf.constant('Hello, tensorflow')

In [4]:
sess.run(hello)

b'Hello, tensorflow'

In [5]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [6]:
a = tf.constant(1, name='input_a')
b = tf.constant(2, name='input_b')

c = tf.multiply(a,b, name='mul_c')
d = tf.multiply(a,b, name='nul_d')

e = tf.add(c,d, name='add_e')

In [7]:
sess.run(e)

4

In [8]:
writer = tf.summary.FileWriter('./my_graph', sess.graph)

In [9]:
from IPython.display import Image 

In [10]:
writer.close()
sess.close()

In [11]:
! tensorboard --logdir='./my_graph'

TensorBoard 1.9.0 at http://OSdeMac.local:6006 (Press CTRL+C to quit)
W0716 16:59:52.154130 Thread-4 application.py:293] path /[[_dataImageSrc]] not found, sending 404
W0716 16:59:52.185466 Thread-4 application.py:293] path /[[_imageURL]] not found, sending 404
^C


# shape, size, rank, reshape

In [13]:
sess1 = tf.InteractiveSession()

/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/client/session.py:1714: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


In [14]:
x = tf.constant([[2,4,3,6],[2,4,9,5],[6,7,4,5],[6,8,3,1]])

In [16]:
x.eval()

array([[2, 4, 3, 6],
       [2, 4, 9, 5],
       [6, 7, 4, 5],
       [6, 8, 3, 1]], dtype=int32)

In [22]:
x.shape

TensorShape([Dimension(4), Dimension(4)])

In [24]:
tf.shape(x).eval()

array([4, 4], dtype=int32)

In [26]:
tf.size(x).eval()

16

In [27]:
tf.rank(x).eval()

2

In [30]:
tf.reshape(x, [2,8]).eval()

array([[2, 4, 3, 6, 2, 4, 9, 5],
       [6, 7, 4, 5, 6, 8, 3, 1]], dtype=int32)

# squeeze
- remove 1d in tensor: **array([1, 4, 4] -> array([4, 4] **

In [49]:
x = tf.constant([[[2,4,3,6],[2,4,9,5],[6,7,4,5],[6,8,3,1]]])

In [50]:
tf.rank(x).eval()

3

In [51]:
tf.shape(x).eval()

array([1, 4, 4], dtype=int32)

In [52]:
x.eval()

array([[[2, 4, 3, 6],
        [2, 4, 9, 5],
        [6, 7, 4, 5],
        [6, 8, 3, 1]]], dtype=int32)

In [53]:
z = tf.squeeze(x).eval()

In [55]:
z

array([[2, 4, 3, 6],
       [2, 4, 9, 5],
       [6, 7, 4, 5],
       [6, 8, 3, 1]], dtype=int32)

In [57]:
tf.shape(z).eval()

array([4, 4], dtype=int32)

# expand dimension
```python
# 't2' is a tensor of shape [2, 3, 5]
tf.shape(tf.expand_dims(t2, 0))  # [1, 2, 3, 5]
tf.shape(tf.expand_dims(t2, 2))  # [2, 3, 1, 5]
tf.shape(tf.expand_dims(t2, 3))  # [2, 3, 5, 1]
```
```python
array([2, 4, 4]
      
    0/-4: _, 2, 4, 4
    1/-3: 2, _, 4, 4
    2/-2: 2, 4, _, 4
    3/-1, 2, 4, 4, _
    _ = 1
```


In [80]:
x = tf.constant([[[2,4,3,6],[2,4,9,5],[6,7,4,5],[6,8,3,1]],[[2,4,3,6],[2,4,9,5],[6,7,4,5],[6,8,3,1]]])

In [81]:
tf.shape(x).eval()

array([2, 4, 4], dtype=int32)

In [82]:
x.eval()

array([[[2, 4, 3, 6],
        [2, 4, 9, 5],
        [6, 7, 4, 5],
        [6, 8, 3, 1]],

       [[2, 4, 3, 6],
        [2, 4, 9, 5],
        [6, 7, 4, 5],
        [6, 8, 3, 1]]], dtype=int32)

In [104]:
z = tf.expand_dims(x,0)

In [105]:
tf.shape(z).eval()

array([1, 2, 4, 4], dtype=int32)

In [106]:
z.eval()

array([[[[2, 4, 3, 6],
         [2, 4, 9, 5],
         [6, 7, 4, 5],
         [6, 8, 3, 1]],

        [[2, 4, 3, 6],
         [2, 4, 9, 5],
         [6, 7, 4, 5],
         [6, 8, 3, 1]]]], dtype=int32)

# How to create tensors

In [107]:
import numpy as np

In [108]:
a = np.array([[2,3],[1,2]], dtype='int32')
b = np.array([[1,0],[2,1]], dtype='int32')

In [111]:
a

array([[2, 3],
       [1, 2]], dtype=int32)

In [112]:
b

array([[1, 0],
       [2, 1]], dtype=int32)

In [109]:
sess = tf.InteractiveSession()

/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/client/session.py:1714: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


In [110]:
tf.add(a,b).eval()

array([[3, 3],
       [3, 3]], dtype=int32)

# Matrix operations 矩阵属性

In [113]:
tf.matmul(a,b).eval()

array([[8, 3],
       [5, 2]], dtype=int32)

In [123]:
x = tf.constant([[1,2,3],[4,5,6]], dtype='float32')
y = tf.constant([[1,1,1],[5,7,5],[2,1,3]], dtype='float32')

In [124]:
tf.matmul(x,y).eval()

array([[17., 18., 20.],
       [41., 45., 47.]], dtype=float32)

In [125]:
tf.matrix_inverse(y).eval() #逆矩阵

array([[ 8.000002  , -1.0000002 , -1.        ],
       [-2.5000005 ,  0.50000006, -0.        ],
       [-4.5000005 ,  0.5000001 ,  1.        ]], dtype=float32)

```
TypeError: Value passed to parameter 'input' has DataType int32 not in list of allowed values: float64, float32, complex64, complex128
```

In [126]:
tf.transpose(x).eval()

array([[1., 4.],
       [2., 5.],
       [3., 6.]], dtype=float32)

In [128]:
tf.matrix_determinant(y).eval() #矩阵行列式

2.0

In [129]:
tf.matrix_solve(y, [[10],[10],[10]]).eval() #solve function x1 + x2 + x3 = 10, 5x1 + 7x2 + 5x3 = 10, 2x1 + x2 + 3x3 = 10

array([[ 60.00001 ],
       [-20.000004],
       [-30.000004]], dtype=float32)

# Reductions

In [130]:
x = tf.constant([[1,2,3],[4,5,6],[7,8,9]])

In [131]:
tf.reduce_prod(x).eval()

362880

In [132]:
1*2*3*4*5*6*7*8*9

362880

In [133]:
tf.reduce_prod(x, reduction_indices=1).eval()

array([  6, 120, 504], dtype=int32)

In [134]:
tf.reduce_max(x, reduction_indices=1).eval()

array([3, 6, 9], dtype=int32)

In [135]:
tf.reduce_min(x, reduction_indices=1).eval()

array([1, 4, 7], dtype=int32)

In [136]:
tf.reduce_mean(x, reduction_indices=1).eval()

array([2, 5, 8], dtype=int32)

# About Boolean

In [137]:
x = tf.constant([[True,False,True],[True,True,True],[False,False,False]])

In [138]:
tf.reduce_all(x, reduction_indices=1).eval() #logic and

array([False,  True, False])

In [139]:
tf.reduce_any(x, reduction_indices=1).eval() #logic or

array([ True,  True, False])

# Slicing

In [5]:
sess = tf.InteractiveSession()

In [6]:
matrix = tf.constant([[1,2,3],[4,5,6],[7,8,9]])

In [7]:
matrix.eval()

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)

In [8]:
tf.slice(matrix, [0,1], [3,2]).eval() # 顶点（左上），shape

array([[2, 3],
       [5, 6],
       [8, 9]], dtype=int32)

# array spliting

In [9]:
arr1 = tf.constant([1,2,3,4,5,6,7,8,])

In [10]:
z = tf.split(arr1, [2,6], 0) # 2개,6개, axis=0

In [11]:
z[0].eval()

array([1, 2], dtype=int32)

In [12]:
z[1].eval()

array([3, 4, 5, 6, 7, 8], dtype=int32)

# matrix spliting

In [13]:
y = tf.split(matrix, [2,1], 1) # 2cols,1col, axis=1

In [14]:
y[0].eval()

array([[1, 2],
       [4, 5],
       [7, 8]], dtype=int32)

In [15]:
y[1].eval()

array([[3],
       [6],
       [9]], dtype=int32)

# padding

In [16]:
matrix.eval()

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)

In [19]:
# [ [上，下]，[左，右] ]加0的个数
tf.pad(matrix,[[0,0],[2,2]]).eval() #上下加0个0，左右加2个0

array([[0, 0, 1, 2, 3, 0, 0],
       [0, 0, 4, 5, 6, 0, 0],
       [0, 0, 7, 8, 9, 0, 0]], dtype=int32)

In [23]:
tf.pad(matrix,[[1,1],[2,2]], "SYMMETRIC").eval()

array([[2, 1, 1, 2, 3, 3, 2],
       [2, 1, 1, 2, 3, 3, 2],
       [5, 4, 4, 5, 6, 6, 5],
       [8, 7, 7, 8, 9, 9, 8],
       [8, 7, 7, 8, 9, 9, 8]], dtype=int32)

# concat